<netmiko.cisco.cisco_ios.CiscoIosSSH object at 0x7fe444010f90>, <netmiko.cisco.cisco_ios.CiscoIosSSH object at 0x7fe44401b190>]
raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required